translator/routes/web.php
<?php

use App\Http\Controllers\LanguageSwitcherController;
use App\Http\Controllers\WordsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('language')->group(function () {
    Route::get('/', [WordsController::class, 'index'])->middleware(['auth']);
    Route::resource('words', WordsController::class)->middleware('auth');
    Auth::routes();
});
Route::get('language/{locale}', [LanguageSwitcherController::class, 'switcher'])
    ->name('language.switcher')
    ->where('locale', 'en|ru');

translator/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * @return HasMany
     */
    public function words(): HasMany
    {
        return $this->hasMany(Word::class);
    }
}

translator/app/Models/Word.php
<?php

namespace App\Models;

use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Word extends Model implements TranslatableContract
{
    use HasFactory;
    use Translatable;

    public $translatedAttributes = ['word'];
    protected $fillable = ['user_id'];

    /**
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return HasMany
     */
    public function translations(): HasMany
    {
        return $this->hasMany(WordTranslation::class);
    }

}

translator/app/Models/WordTranslation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class WordTranslation extends Model
{
    public $timestamps = false;
    protected $fillable = ['word'];

    /**
     * @return BelongsTo
     */
    public function phrase(): BelongsTo
    {
        return $this->belongsTo(Word::class);
    }
}

translator/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

translator/app/Http/Controllers/LanguageSwitcherController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class LanguageSwitcherController extends Controller
{

    /**
     * @param Request $request
     * @param string $locale
     * @return RedirectResponse
     */
    public function switcher(Request $request, string $locale)
    {
        $request->session()->put('locale', $locale);
        return back();
    }
}

translator/app/Http/Controllers/WordsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Word;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class WordsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $words = Word::all();
        return view('words.index', compact('words'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request): RedirectResponse
    {
        $data = ['user_id' => auth()->user()->id, 'en' => ['word' => ''], 'ru' => ['word' => $request->input('ru')],
            'fr' => ['word' => ''], 'de' => ['word' => ''], 'gr' => ['word' => '']];
        $word = Word::create($data);
        $word->save();
        return redirect()->route('words.index')->with('status', "{$word->word} successfully created!");
    }

    /**
     * Display the specified resource.
     *
     * @param Word $word
     * @return Application|Factory|View
     */
    public function show(word $word)
    {
        return view('words.show', compact('word'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Word $word
     * @return RedirectResponse
     */
    public function update(Request $request, Word $word)
    {
        $data = [
            'en' => ['word' => $request->input('en') ? $request->input('en') : ''],
            'fr' => ['word' => $request->input('fr') ? $request->input('fr') : ''],
            'de' => ['word' => $request->input('de') ? $request->input('de') : ''],
            'gr' => ['word' => $request->input('gr') ? $request->input('gr') : ''],
        ];
        if ($data['en']['word'] == '') {
            foreach ($word->translations as $translation) {
                if ($translation->locale == 'en') {
                    $data['en'] = ['word' => $translation->word];
                }
            }
        } if ($data['fr']['word'] == '') {
            foreach ($word->translations as $translation) {
                if ($translation->locale == 'fr') {
                    $data['fr'] = ['word' => $translation->word];
                }
            }
        } if ($data['de']['word'] == '') {
            foreach ($word->translations as $translation) {
                if ($translation->locale == 'de') {
                    $data['de'] = ['word' => $translation->word];
                }
            }
        } if ($data['gr']['word'] == '') {
            foreach ($word->translations as $translation) {
                if ($translation->locale == 'gr') {
                    $data['gr'] = ['word' => $translation->word];
                }
            }
        }
        $word->update($data);
        return back();
    }
}

translator/resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    @lang('messages.translator')
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand btn btn-outline-primary" href="{{route('words.index')}}">@lang('messages.words')</a>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                        <select class="custom-select" onchange="location = this.value;" id="">
                            <option @if(session('locale') == 'en') selected
                                    @endif value="{{route('language.switcher', ['locale' => 'en'])}}">EN
                            </option>
                            <option @if(session('locale') == 'ru') selected
                                    @endif value="{{route('language.switcher', ['locale' => 'ru'])}}">RU
                            </option>
                        </select>
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

translator/resources/views/words/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            @foreach($words as $word)
                <div class="col" style="padding: 35px 0 0 0;" id="delete-article-{{$word->id}}">
                    <div class="card" style="width: 18rem;">
                        <div class="card-header">
                            <a href="{{route('words.show', ['word' => $word])}}"
                               class="card-link">{{$word->translate('ru')->word}}</a>
                            <br>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
    <div class="container">
        <h1 class="m-5">@lang('messages.order')</h1>
        <form method="post" action="{{ route('words.store') }}">
            @csrf
            <div class="form-group">
                <label for="ru">@lang('messages.name')</label>
                <input type="text" class="form-control @error('ru') is-invalid @enderror" id="ru" name="ru"
                       value="word"/>
                @error('ru')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <button type="submit" class="btn btn-primary">@lang('messages.order_translation')</button>
        </form>
    </div>
@endsection

translator/resources/views/words/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-3">
                <form method="post" action="{{ route('words.update', ['word' => $word])}}">
                    @method('put')
                    @csrf
                    @foreach($word->translations as $translation)
                        <div class="col" style="padding: 35px 0 0 0;">
                            <div class="card" style="width: 18rem;">
                                <div class="card-header">
                                    @if($translation->locale == 'ru')
                                        <p>@lang('languages.russian')</p>
                                    @endif
                                    @if($translation->locale == 'en')
                                        <p>@lang('languages.english')</p>
                                    @endif
                                    @if($translation->locale == 'gr')
                                        <p>@lang('languages.greece')</p>
                                    @endif
                                    @if($translation->locale == 'de')
                                        <p>@lang('languages.german')</p>
                                    @endif
                                    @if($translation->locale == 'fr')
                                        <p>@lang('languages.french')</p>
                                    @endif
                                    @if($translation->word != '')
                                        <p>{{$translation->word}}</p>
                                    @else
                                        <div class="form-group">
                                            <input type="text"
                                                   class="form-control"
                                                   id="{{$translation->locale}}" name="{{$translation->locale}}"
                                                   value="{{$translation->word}}"/>
                                        </div>
                                    @endif
                                </div>
                            </div>
                        </div>
                    @endforeach
                    <br>
                    <button type="submit" class="btn btn-primary">@lang('messages.save_translations')</button>
                </form>
            </div>
        </div>
    </div>
@endsection